name: Release using conventional commits (master branch)

on:
  push:
    branches:
      - master

# 1) Let the workflow write commits/tags
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # 2) Checkout with full history so tags work
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # (Optional) Set git identity, some actions expect it
      - name: Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # 3) Generate changelog + commit + tag (uses token to push)
      - name: Conventional Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # optional, but explicit:
          release-branches: master
          preset: conventionalcommits

      # 4) Create GitHub Release only if a new version was created
      - name: Create Release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          draft: false
          prerelease: false
